/**
 * @remarks
 * Error that is thrown if somehow there are a mix of numbers and bigs in the range.
 * This should never happen but the typescript compiler doesn't know that.
 */
export class RangelyDefinitionError extends Error {
    // tslint:disable-next-line:max-line-length
    public readonly message = "Found mix of numbers and Bigs in the RangeDefinition generated by rangely. This shouldn't be possible.";
}
